Inside loop
Exception in Loop
